### ISSUE TITLE
Missing history directive

### ISSUE THREAD

**Issue by charlieharris1** [igiveadamn/ccdb#10]
It looks like this file no longer exists so can we remove the script tag referencing it? https://github.com/igiveadamn/ccdb/blob/master/src/client/index.html#L46

**Comment by charlieharris1** [comment]
@andy-duncan can you confirm whether or not we need this?

**Comment by igiveadamn** [comment]
history is gone. I'm in the middle of some work to clean up the forms.

the referral forms and admission forms should all look like they are
supposed to. I think the schema might need a bit of tweaking.

but I won;'t get to this for another 2 weeks, as I am going away, so I know
it is a bit broken at the moment.
