### ISSUE TITLE
Fix login

### ISSUE THREAD

**Issue by charlieharris1** [igiveadamn/ccdb#11]
Before login you cannot click on on any of the tabs. As soon as you enter any combination of username and pwd its possible to view the contents of those pages even though you are unauthorised.

**Comment by charlieharris1** [comment]
I've implemented a fix for this but feel that it could be made more robust: https://github.com/igiveadamn/ccdb/commit/a140211720d51153fdbc4625fc36783df61710f0#diff-b2ce957df304528e922f12debf710033R32.

It might be good to return a status code [here](https://github.com/igiveadamn/ccdb/commit/a140211720d51153fdbc4625fc36783df61710f0#diff-b2ce957df304528e922f12debf710033R32) and add some validation of the response data.

**Comment by andy-duncan** [comment]
ok. or it might be sufficient just to check the status code, and the existence of the user object.

**Comment by charlieharris1** [comment]
Now checks if there is a user object: https://github.com/igiveadamn/ccdb/commit/2590646afd9f8604eb0f9a49f44928f01939a5d7
