### ISSUE TITLE
Only show reset password success message if username is valid

### ISSUE THREAD

**Issue by charlieharris1** [igiveadamn/ccdb#12]
Currently we show success message even if a username does not exist in the db.

**Comment by andy-duncan** [comment]
I'm ok with that.

I don't think it's a big deal, but e.g. datadog, says something like, 'an email has been sent, if a user with that email exists'.

Basically, just prevents discovering whether a user has a login, from that form.

**Comment by charlieharris1** [comment]
I've reworded the message
