### ISSUE TITLE
Form tabs should be stacked vertically with some spacing

### ISSUE THREAD

**Issue by charlieharris1** [igiveadamn/ccdb#21]

**Comment by charlieharris1** [comment]
@igiveadamn with the number of tabs we have I don't think this will look particularly nice and will mean our users have to scroll quite far down the page to fill in the forms:

<img width="1276" alt="screen shot 2016-08-07 at 08 17 21" src="https://cloud.githubusercontent.com/assets/11438777/17461087/98771da8-5c77-11e6-9867-02c819779fa6.png">

Let me know what you think.

**Comment by igiveadamn** [comment]
Yes. I was thinking just an asterisk. Next to the field, or a border. Something like that?

**Comment by charlieharris1** [comment]
@igiveadamn I'm not sure I follow. Are you referring to the field level validation here? Those suggestions sound good (and I'll get on it now) but I was talking about whether or not we want stacked tabs (which I think is something Rob wanted a while back?).

**Comment by igiveadamn** [comment]
Sorry. Image was small on my phone. I thought those were field level. 

No. Tabs can stay just as they are.
