### ISSUE TITLE
Should there be a referral button in patient search results?

### ISSUE THREAD

**Issue by charlieharris1** [igiveadamn/ccdb#27]
On the dashboard there are two referral options; emergency and elective. No such options are available in the search results list so I'm wondering if the referral button should be there or if we need a way to let users decide if it is elective or emergency.

<img width="1158" alt="screen shot 2016-08-07 at 11 06 58" src="https://cloud.githubusercontent.com/assets/11438777/17461758/20612a80-5c8f-11e6-96e3-f2113423b8fd.png">

**Comment by igiveadamn** [comment]
This button is just a way to get back to the referral details for an
existing patient.

The patient needs to have been created with either emergency or elective,
so all patients in the search results, will already have that value set,
and display accordingly.
