### ISSUE TITLE
make fields mandatory at different stages

### ISSUE THREAD

**Issue by igiveadamn** [igiveadamn/ccdb#3]
i.e. when completing referral, all referral fields should be required
then when completing admission, all admission fields should be required
etc.

**Comment by andy-duncan** [comment]
but how do we tell the user if something is missing on another tab?

and how do we expect the user to navigate between tabs?

**Comment by andy-duncan** [comment]
@charlieharris1 has done all this. satisfactory for now. might need to consider a way to make the fields invalid only after the first time you've moved past that tab (or something similar)
